---
# tasks file for kibana
- name: Install selinux bindings
  yum: name="libselinux-python" state="present"

- name: Copy repository definition file
  template: src=kibana.repo.j2 dest=/etc/yum.repos.d/kibana.repo

- name: Import Elasticsearch RPM key
  rpm_key: state="present" key="https://packages.elastic.co/GPG-KEY-elasticsearch"

- name: Install Java and Kibana
  yum: state="present" name="{{ item }}"
  with_items:
    - java-1.8.0-openjdk
    - kibana

- name: Start and enable kibana service
  service: name="kibana" state="started" enabled=Yes