---
# tasks file for basic
- name: Install basic packages
  yum:
    name: "{{ item }}"
    state: "present"
  with_items:
    - nano
    - wget
    - bash-completion
    - epel-release
    - libselinux-python

- name: Harden OS
  include: os_hardning.yml

- name: Create user
  user:
    name: "{{ item.name }}"
    groups: "{{ item.groups|join(',') }}"
  with_items: "{{ users }}"

- name: Place SSH key
  authorized_key:
    user: "{{ item.name }}"
    key: "{{ item.ssh_key }}"
    exclusive: yes
  with_items: "{{ users }}"

- name: Remove keys for root user
  authorized_key:
    user: root
    key: ""
    exclusive: yes

- name: Enable passwordless sudo for users in wheel group
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%wheel\s*ALL='
    line: '%wheel     ALL=(ALL)    NOPASSWD: ALL'
    validate: 'visudo -cf %s'