---
- name: Enable Stack protection
  sysctl:
    name: "kernel.randomize_va_space"
    value: 2

- name: Enabel link protection
  sysctl:
    name: "{{ item }}"
    value: 1
  with_items:
    - fs.protected_symlinks
    - fs.protected_hardlinks

- name: Create systemd configuration file for Core Dumps
  file:
    path: "/etc/systemd/coredump.conf"
    state: "touch"

- name: Disable core dump by configuring systemd
  copy:
    dest: "/etc/systemd/coredump.conf"
    content: "Storage=none"

