---
# tasks file for sshd
- name: Ensure OpenSSH is installed and at the latest version
  yum:
    name: "openssh-server"
    state: "latest"

- name: Configure SSH daemon
  template:
    src: "templates/sshd_config.j2"
    dest: "/etc/ssh/sshd_config"

- name: Restart SSH daemon
  service:
    name: "sshd"
    state: "restarted"